name = "TropicalHomotopies"
uuid = "d6b0309f-5444-47e3-b743-85b0b50b5d05"
authors = ["oliverdaisey <oliverjdaisey@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "1.2.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
